<?php

namespace Nzo\TunisiefretBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DemandeExportPostuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeExportPostuleRepository extends EntityRepository
{
    public function getDemandeExportPostuleByDemande($id)
    {
         $qb = $this->createQueryBuilder('a');
         $qb->where('a.demandeexport = :demandeexport')
            ->setParameter('demandeexport', $id)
            ->orderBy('a.datepostule', 'DESC');
         return $qb->getQuery()->execute();
    }   
    
}
