nzo_tunisiefret_homepage:
    pattern:  /
    defaults: { _controller: NzoTunisiefretBundle:Front:index }
    
nzo_inscription:
    pattern:  /inscription/
    defaults: { _controller: NzoTunisiefretBundle:Front:inscription }
    
nzo_contact:
    pattern: /contact/
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'NzoTunisiefretBundle:Front:contact.html.twig'
        
nzo_apropos:
    pattern: /a-propos/
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'NzoTunisiefretBundle:Front:apropos.html.twig'        
        
        
#CLIENT ROUTE    
nzo_poserdemande_export:
    pattern: /poser-demande-export/
    defaults: {_controller: NzoTunisiefretBundle:Client:PoserDemandeExport}
    
ajax_send_msg_client:
    pattern: /message-client-send/
    defaults: {_controller: NzoTunisiefretBundle:Client:MessageClientSend}
    
ajax_get_notif_client:
    pattern: /liste-notif-client/ajax/
    defaults: {_controller: NzoTunisiefretBundle:Client:AjaxGetNotif}   
    
ajax_get_nb_notif_client:
    pattern: /nb-notif-client/ajax/
    defaults: {_controller: NzoTunisiefretBundle:Client:AjaxGetNbNotif}    
    
ajax_get_nb_msg_client:
    pattern: /nb-msg-client/ajax/
    defaults: {_controller: NzoTunisiefretBundle:Client:AjaxGetNbMsg}       
    
client_list_notifications:
    pattern: /liste-notifications/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeNotifications}        
    
client_list_messages:
    pattern: /liste-messages/
    defaults: {_controller: NzoTunisiefretBundle:Client:Listemessages}    
    
nzo_voirlistedemande_export_active:
    pattern: /liste-demande-export/active/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeDemandeExportActive}
    
nzo_voirlistedemande_export_archive:
    pattern: /liste-demande-export/archive/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeDemandeExportArchive}    
    
client_list_demande_type:
    pattern: /liste-demande-type/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeDemandeExportType}    

client_contrat_encours:
    pattern: /liste-contrat-encours/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeContratEncours}    

client_contrat_terminer:
    pattern: /liste-contrat-terminé/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeContratTerminer}
    
client_notifmsg_url_val:  
    pattern: /client/message/{id}/valeur/
    defaults: {_controller: NzoTunisiefretBundle:Client:MessageUrlValeur}  
    requirements:
        id:  \d+    
        
client_notif_url_val:  
    pattern: /client/notification/{id}/valeur/
    defaults: {_controller: NzoTunisiefretBundle:Client:NotificationUrlValeur}  
    requirements:
        id:  \d+        
    
client_liste_contrat_encours:  
    pattern: /liste-contrats/{id}/encours/
    defaults: {_controller: NzoTunisiefretBundle:Client:ContratEncours}  
    requirements:
        id:  \d+     
    
client_demande_export_termine_detail:  
    pattern: /demande-export/{id}/termine/
    defaults: {_controller: NzoTunisiefretBundle:Client:DemandeExportTermineDetail}  
    requirements:
        id:  \d+   

client_demande_export_active:    
    pattern: /demande-export/{id}/active/
    defaults: {_controller: NzoTunisiefretBundle:Client:DemandeExportActive}  
    requirements:
        id:  \d+ 

client_postule_active_detail:
    pattern: /postule-active/{id}/detail/
    defaults: {_controller: NzoTunisiefretBundle:Client:DetailPostuleActive}  
    requirements:
        id:  \d+ 
        
client_demande_export_archive:    
    pattern: /demande-export/{id}/archive/
    defaults: {_controller: NzoTunisiefretBundle:Client:DemandeExportArchive}  
    requirements:
        id:  \d+ 
        
client_postule_archive_detail:
    pattern: /postule-archive/{id}/detail/
    defaults: {_controller: NzoTunisiefretBundle:Client:DetailPostuleArchive}  
    requirements:
        id:  \d+ 

client_demande_export_encours_detail:
    pattern: /demande-export/{id}/encours/detail/
    defaults: {_controller: NzoTunisiefretBundle:Client:DemandeExportEnCoursDetail}  
    requirements:
        id:  \d+
        
client_postule_encours_detail:
    pattern: /postule-encours/{id}/detail/
    defaults: {_controller: NzoTunisiefretBundle:Client:DetailPostuleEnCours}  
    requirements:
        id:  \d+         
        
client_postule_encours_detail_afterdone:
    pattern: /postule/encours/{id}/detail/
    defaults: {_controller: NzoTunisiefretBundle:Client:DetailPostuleEnCoursAfterDone}  
    requirements:
        id:  \d+        
        
client_terminer_demande:        
    pattern: /terminer-demande-export/{id}
    defaults: {_controller: NzoTunisiefretBundle:Client:TerminerDemandeExport}  
    requirements:
        id:  \d+
        
client_annuler_demande:        
    pattern: /annuler-demande-export/{id}
    defaults: {_controller: NzoTunisiefretBundle:Client:AnnulerDemandeExport}  
    requirements:
        id:  \d+     

client_contrat_confirmer:
    pattern: /contrat-export/{id}/confirmer/
    defaults: {_controller: NzoTunisiefretBundle:Client:ConfirmerContratExport}     
        
nzo_detaildemande_export_type:    
    pattern: /detail-demande-export/{id}/type/
    defaults: {_controller: NzoTunisiefretBundle:Client:DetailDemandeExportType}  
    requirements:
        id:  \d+          
               
client_supprimer_demande_type:    
    pattern: /demande-export-type/{id}/supprimer/
    defaults: {_controller: NzoTunisiefretBundle:Client:SupprimerDemandeExportType}  
    requirements:
        id:  \d+            
  
client_reposter_demande_type:  
    pattern: /demande-export-type/{id}/reposter/
    defaults: {_controller: NzoTunisiefretBundle:Client:ReposterDemandeExportType}  
    requirements:
        id:  \d+             
  
client_donner_avis_demande_export:  
    pattern: /demande-export/{id}/ajout-avis/
    defaults: {_controller: NzoTunisiefretBundle:Client:DonnerAvisDemandeExport}  
    requirements:
        id:  \d+  
  
  
#EXPORTATEUR ROUTE
exp_home:
    pattern: /liste-demande-export/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:Home}

nzo_postuledemande_export:
    pattern: /postule-demande-export/{id}
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:PostuleDemandeExport}  
    requirements:
        id:  \d+       

ajax_get_nb_notif_exportateur:
    pattern: /nb-notif-exportateur/ajax/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:AjaxGetNbNotif}    
    
ajax_get_nb_msg_exportateur:
    pattern: /nb-msg-exportateur/ajax/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:AjaxGetNbMsg}     
    
ajax_get_notif_exportateur:
    pattern: /liste-notif-exportateur/ajax/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:AjaxGetNotif}    
    
exp_liste_postule_active:
    pattern: /liste-postule-active/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ListePostuleActive}

exp_liste_postule_archive:
    pattern: /liste-postule-archive/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ListePostuleArchive}

exp_notifmsg_url_val:  
    pattern: /exportateur/message/{id}/valeur/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:MessageUrlValeur}  
    requirements:
        id:  \d+ 
      
exp_notif_url_val:  
    pattern: /exportateur/notification/{id}/valeur/
    defaults: {_controller: NzoTunisiefretBundle:Client:NotificationUrlValeur}  
    requirements:
        id:  \d+         
        
exp_detail_postule_active:    
    pattern: /detail-postule/{id}/active/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:DetailPostuleActive}  
    requirements:
        id:  \d+   

exp_list_messages:
    pattern: /exportateur/liste-messages/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:Listemessages}
    
exp_detail_postule_archive:    
    pattern: /detail-postule/{id}/archive/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:DetailPostuleArchive}  
    requirements:
        id:  \d+                 

exp_annuler_postule:        
    pattern: /supprimer-postule/{id}
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:AnnulerPostule}  
    requirements:
        id:  \d+
        
exp_contrat_encours_detail:        
    pattern: /contrat-encours/{id}/detail/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ContratEnCoursDetail}  
    requirements:
        id:  \d+        

exp_contrat_termine_detail:  
    pattern: /contrat-termine/{id}/detail/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ContratTermineDetail}  
    requirements:
        id:  \d+  
        
exp_liste_contrats_en_cours:
    pattern: /liste-contrat/encours/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ListeContratEnCours}
    
exp_liste_contrats_termine:
    pattern: /liste-contrat/termine/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ListeContratTermine}

exp_list_notifications:
    pattern: /exportateur/liste-notifications/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ListeNotifications}
    
ajax_send_msg_exportateur:
    pattern: /message-exportateur-send/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:MessageExportateurSend}    
    
exp_donner_avis_demande_export:  
    pattern: /exportateur/demande-export/{id}/ajout-avis/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:DonnerAvisDemandeExport}  
    requirements:
        id:  \d+    
    
#--------------------------- FosUserBundle -----------------------------------
client_registration:
    pattern:  /inscription/client
    defaults: { _controller: NzoUserBundle:RegistrationClient:register }
    
#client_edite_profil:
#    pattern:  /profil/client/edite
#    defaults: { _controller: NzoUserBundle:ProfileClient:edit }    
    
exportateur_registration:
    pattern:  /inscription/exportateur
    defaults: { _controller: NzoUserBundle:RegistrationExportateur:register }

    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

   

fos_user_registration_check_email:
    pattern: /check-email
    defaults: { _controller: FOSUserBundle:Registration:checkEmail }
    requirements:
      _method: GET
      
fos_user_registration_confirm:
    pattern: /inscription/confirmer/{token}
    defaults: { _controller: FOSUserBundle:Registration:confirm }
    requirements:
      _method: GET
      
fos_user_registration_confirmed:
    pattern: /inscription/confirmer
    defaults: { _controller: FOSUserBundle:Registration:confirmed }
    requirements:
      _method: GET    
      
# modif bundle to NzoUser      
fos_user_change_password: 
    pattern: /change-password
    defaults: { _controller: NzoUserBundle:ChangePassword:changePassword } 
    requirements:
      _method: GET|POST   
      
      
fos_user_resetting_request:
    pattern: /request
    defaults: { _controller: FOSUserBundle:Resetting:request }
    requirements:
      _method: GET

fos_user_resetting_send_email:
    pattern: /send-email
    defaults: { _controller: FOSUserBundle:Resetting:sendEmail }
    requirements:
      _method: POST

fos_user_resetting_check_email:
    pattern: /check-email
    defaults: { _controller: FOSUserBundle:Resetting:checkEmail }
    requirements:
      _method: GET

fos_user_resetting_reset:
    pattern: /reset/{token}
    defaults: { _controller: FOSUserBundle:Resetting:reset }
    requirements:
      _method: GET|POST

#--------------------------- babababababababaab -----------------------------------
# ADMIN

admin_liste_clients:
    pattern: /admin/liste-clients/
    defaults: { _controller: NzoTunisiefretBundle:Admin:ListeClients }

admin_liste_exportateurs:
    pattern: /admin/liste-exportateurs/
    defaults: { _controller: NzoTunisiefretBundle:Admin:ListeExportateurs }
        