nzo_tunisiefret_homepage:
    pattern:  /
    defaults: { _controller: NzoTunisiefretBundle:Front:index }
    
nzo_inscription:
    pattern:  /inscription/
    defaults: { _controller: NzoTunisiefretBundle:Front:inscription }
    
nzo_contact:
    pattern: /contact/
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'NzoTunisiefretBundle:Front:contact.html.twig'
        
nzo_apropos:
    pattern: /a-propos/
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'NzoTunisiefretBundle:Front:apropos.html.twig'        
        
        
#CLIENT ROUTE    
nzo_poserdemande_export:
    pattern: /poser-demande-export/
    defaults: {_controller: NzoTunisiefretBundle:Client:PoserDemandeExport}
    
ajax_send_msg_client:
    pattern: /message-client-send/
    defaults: {_controller: NzoTunisiefretBundle:Client:MessageClientSend}
    
nzo_voirlistedemande_export_active:
    pattern: /liste-demande-export/active/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeDemandeExportActive}
    
nzo_voirlistedemande_export_archive:
    pattern: /liste-demande-export/archive/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeDemandeExportArchive}    
    
client_list_demande_type:
    pattern: /liste-demande-type/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeDemandeExportType}    

client_contrat_encours:
    pattern: /liste-contrat-encours/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeContratEncours}    

client_contrat_terminer:
    pattern: /liste-contrat-terminé/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeContratTerminer}

nzo_detaildemande_export:    
    pattern: /detail-demande-export/{id}
    defaults: {_controller: NzoTunisiefretBundle:Client:DetailDemandeExport}  
    requirements:
        id:  \d+ 

client_terminer_demande:        
    pattern: /terminer-demande-export/{id}
    defaults: {_controller: NzoTunisiefretBundle:Client:TerminertDemandeExport}  
    requirements:
        id:  \d+
        
client_annuler_demande:        
    pattern: /annuler-demande-export/{id}
    defaults: {_controller: NzoTunisiefretBundle:Client:AnnulerDemandeExport}  
    requirements:
        id:  \d+ 
        
nzo_detaildemande_export_postule:    
    pattern: /detail-demande-export/{id}/postule/
    defaults: {_controller: NzoTunisiefretBundle:Client:DetailDemandeExportPostule}  
    requirements:
        id:  \d+    

client_reposter_demande_terminer:
    pattern: /demande-terminé/{id}/reposter/
    defaults: {_controller: NzoTunisiefretBundle:Client:ReposterDemandeExportTerminer}  
    requirements:
        id:  \d+      
        
nzo_detaildemande_export_type:    
    pattern: /detail-demande-export/{id}/type/
    defaults: {_controller: NzoTunisiefretBundle:Client:DetailDemandeExportType}  
    requirements:
        id:  \d+          
        
        
client_supprimer_demande_type:    
    pattern: /demande-export-type/{id}/supprimer/
    defaults: {_controller: NzoTunisiefretBundle:Client:SupprimerDemandeExportType}  
    requirements:
        id:  \d+            
  
client_reposter_demande_type:  
    pattern: /demande-export-type/{id}/reposter/
    defaults: {_controller: NzoTunisiefretBundle:Client:ReposterDemandeExportType}  
    requirements:
        id:  \d+             
  
client_donner_avis_demande_export:  
    pattern: /demande-export/{id}/ajout-avis/
    defaults: {_controller: NzoTunisiefretBundle:Client:DonnerAvisDemandeExport}  
    requirements:
        id:  \d+  
  
  
#EXPORTATEUR ROUTE
nzo_postuledemande_export:
    pattern: /postule-demande-export/{id}
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:PostuleDemandeExport}  
    requirements:
        id:  \d+       

exp_liste_postule_active:
    pattern: /liste-postule-active/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ListePostuleActive}

exp_liste_postule_archive:
    pattern: /liste-postule-archive/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ListePostuleArchive}
    
exp_detail_postule_active:    
    pattern: /detail-postule/{id}/active/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:DetailPostuleActive}  
    requirements:
        id:  \d+         

exp_liste_travail_en_cours:
    pattern: /liste-travail-encours/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ListeTravailEnCours}
    
exp_liste_travail_termine:
    pattern: /liste-travail-termine/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ListeTravailTermine}
    
#--------------------------- FosUserBundle -----------------------------------
client_registration:
    pattern:  /inscription/client
    defaults: { _controller: NzoUserBundle:RegistrationClient:register }
    
#client_edite_profil:
#    pattern:  /profil/client/edite
#    defaults: { _controller: NzoUserBundle:ProfileClient:edit }    
    
exportateur_registration:
    pattern:  /inscription/exportateur
    defaults: { _controller: NzoUserBundle:RegistrationExportateur:register }

    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

   

fos_user_registration_check_email:
    pattern: /check-email
    defaults: { _controller: FOSUserBundle:Registration:checkEmail }
    requirements:
      _method: GET
      
fos_user_registration_confirm:
    pattern: /inscription/confirmer/{token}
    defaults: { _controller: FOSUserBundle:Registration:confirm }
    requirements:
      _method: GET
      
fos_user_registration_confirmed:
    pattern: /inscription/confirmer
    defaults: { _controller: FOSUserBundle:Registration:confirmed }
    requirements:
      _method: GET    
      
# modif bundle to NzoUser      
fos_user_change_password: 
    pattern: /change-password
    defaults: { _controller: NzoUserBundle:ChangePassword:changePassword } 
    requirements:
      _method: GET|POST   
      
      
fos_user_resetting_request:
    pattern: /request
    defaults: { _controller: FOSUserBundle:Resetting:request }
    requirements:
      _method: GET

fos_user_resetting_send_email:
    pattern: /send-email
    defaults: { _controller: FOSUserBundle:Resetting:sendEmail }
    requirements:
      _method: POST

fos_user_resetting_check_email:
    pattern: /check-email
    defaults: { _controller: FOSUserBundle:Resetting:checkEmail }
    requirements:
      _method: GET

fos_user_resetting_reset:
    pattern: /reset/{token}
    defaults: { _controller: FOSUserBundle:Resetting:reset }
    requirements:
      _method: GET|POST

#--------------------------- babababababababaab -----------------------------------
# ADMIN

admin_liste_clients:
    pattern: /admin/liste-clients/
    defaults: { _controller: NzoTunisiefretBundle:Admin:ListeClients }

admin_liste_exportateurs:
    pattern: /admin/liste-exportateurs/
    defaults: { _controller: NzoTunisiefretBundle:Admin:ListeExportateurs }
        