nzo_tunisiefret_homepage:
    pattern:  /
    defaults: { _controller: NzoTunisiefretBundle:Front:index }
    
nzo_inscription:
    pattern:  /inscription/
    defaults: { _controller: NzoTunisiefretBundle:Front:inscription }
    
nzo_contact:
    pattern: /contact/
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'NzoTunisiefretBundle:Front:contact.html.twig'
        
nzo_apropos:
    pattern: /a-propos/
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'NzoTunisiefretBundle:Front:apropos.html.twig'        
        
        
#CLIENT ROUTE    
nzo_poserdemande_export:
    pattern: /deposer-demande-fret/
    defaults: {_controller: NzoTunisiefretBundle:Client:PoserDemandeExport}
    
ajax_send_msg_client:
    pattern: /message-client-send/
    defaults: {_controller: NzoTunisiefretBundle:Client:MessageClientSend}
    
ajax_get_notif_client:
    pattern: /liste-notif-client/ajax/
    defaults: {_controller: NzoTunisiefretBundle:Client:AjaxGetNotif}   
    
ajax_get_nb_notif_client:
    pattern: /nb-notif-client/ajax/
    defaults: {_controller: NzoTunisiefretBundle:Client:AjaxGetNbNotif}    
    
ajax_get_nb_msg_client:
    pattern: /nb-msg-client/ajax/
    defaults: {_controller: NzoTunisiefretBundle:Client:AjaxGetNbMsg}       
    
client_list_notifications:
    pattern: /liste-notifications/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeNotifications}        
    
client_list_messages:
    pattern: /liste-messages/
    defaults: {_controller: NzoTunisiefretBundle:Client:Listemessages}    
    
nzo_voirlistedemande_export_active:
    pattern: /liste-demande-fret/active/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeDemandeExportActive}
    
nzo_voirlistedemande_export_archive:
    pattern: /liste-demande-fret/archive/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeDemandeExportArchive}    
    
client_list_demande_type:
    pattern: /liste-demande-type/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeDemandeExportType}    

client_contrat_encours:
    pattern: /liste-contrat-encours/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeContratEncours}    

client_contrat_terminer:
    pattern: /liste-contrat-terminé/
    defaults: {_controller: NzoTunisiefretBundle:Client:ListeContratTerminer}
    
client_notifmsg_url_val:  
    pattern: /Client-Message_~{id}/Valeur/
    defaults: {_controller: NzoTunisiefretBundle:Client:MessageUrlValeur}      
        
client_notif_url_val:  
    pattern: /Client-Notification_~{id}/Valeur/
    defaults: {_controller: NzoTunisiefretBundle:Client:NotificationUrlValeur}  
        
    
client_liste_contrat_encours:  
    pattern: /Liste-Contrats_~{id}/EnCours/
    defaults: {_controller: NzoTunisiefretBundle:Client:ContratEncours}       
    
client_demande_export_termine_detail:  
    pattern: /Demande-Fret_~{id}/Terminé/
    defaults: {_controller: NzoTunisiefretBundle:Client:DemandeExportTermineDetail}     

client_demande_export_active:    
    pattern: /Demande-Fret-Active_~{id}
    defaults: {_controller: NzoTunisiefretBundle:Client:DemandeExportActive}  
#    requirements:
#        id:  \d+ 

client_postule_active_detail:
    pattern: /Postule-Active_~{id}/Detail/
    defaults: {_controller: NzoTunisiefretBundle:Client:DetailPostuleActive}   
        
client_demande_export_archive:    
    pattern: /Demande-Fret_~{id}/Archive/
    defaults: {_controller: NzoTunisiefretBundle:Client:DemandeExportArchive}   
        
client_postule_archive_detail:
    pattern: /Postule-Archive_~{id}/Detail/
    defaults: {_controller: NzoTunisiefretBundle:Client:DetailPostuleArchive}   
        
client_profil_exportateur:
    pattern: /Profil-Exportateur_~{id}
    defaults: {_controller: NzoTunisiefretBundle:Client:ProfilExportateur}   

client_demande_export_encours_detail:
    pattern: /Demande-Fret_~{id}/EnCours/Detail/
    defaults: {_controller: NzoTunisiefretBundle:Client:DemandeExportEnCoursDetail}  
        
client_postule_encours_detail:
    pattern: /Postule-EnCours_~{id}/Detail/
    defaults: {_controller: NzoTunisiefretBundle:Client:DetailPostuleEnCours}           
        
client_postule_encours_detail_afterdone:
    pattern: /Postule-EnCours-Detail_~{id}
    defaults: {_controller: NzoTunisiefretBundle:Client:DetailPostuleEnCoursAfterDone}         
        
client_terminer_demande:        
    pattern: /Terminer-Demande-Fret_~{id}
    defaults: {_controller: NzoTunisiefretBundle:Client:TerminerDemandeExport}  
        
client_annuler_demande:        
    pattern: /Annuler-Demande-Fret_~{id}
    defaults: {_controller: NzoTunisiefretBundle:Client:AnnulerDemandeExport}  

client_contrat_confirmer:
    pattern: /Contrat-Fret_~{id}/Confirmer/
    defaults: {_controller: NzoTunisiefretBundle:Client:ConfirmerContratExport}     
        
nzo_detaildemande_export_type:    
    pattern: /Demande-Fret-Detail_~{id}/Type/
    defaults: {_controller: NzoTunisiefretBundle:Client:DetailDemandeExportType}            
               
client_supprimer_demande_type:    
    pattern: /Demande-Fret-Type_~{id}/Supprimer/
    defaults: {_controller: NzoTunisiefretBundle:Client:SupprimerDemandeExportType}  
  
client_reposter_demande_type:  
    pattern: /Demande-Fret-Type_~{id}/Deposer/
    defaults: {_controller: NzoTunisiefretBundle:Client:ReposterDemandeExportType}  
  
client_donner_avis_demande_export:  
    pattern: /Demande-Fret_~{id}/Ajout-Avis/
    defaults: {_controller: NzoTunisiefretBundle:Client:DonnerAvisDemandeExport} 
  
  
#EXPORTATEUR ROUTE
exp_home:
    pattern: /liste-demande-export/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:Home}

nzo_postuledemande_export:
    pattern: /Postule-Demande-Fret_~{id}
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:PostuleDemandeExport}  

ajax_get_nb_notif_exportateur:
    pattern: /nb-notif-exportateur/ajax/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:AjaxGetNbNotif}    
    
ajax_get_nb_msg_exportateur:
    pattern: /nb-msg-exportateur/ajax/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:AjaxGetNbMsg}     
    
ajax_get_notif_exportateur:
    pattern: /liste-notif-exportateur/ajax/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:AjaxGetNotif}    
    
exp_liste_postule_active:
    pattern: /liste-postule-active/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ListePostuleActive}

exp_liste_postule_archive:
    pattern: /liste-postule-archive/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ListePostuleArchive}

exp_notifmsg_url_val:  
    pattern: /Exportateur-Message_~{id}/Valeur/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:MessageUrlValeur}  
      
exp_notif_url_val:  
    pattern: /Exportateur-Notification_~{id}/Valeur/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:NotificationUrlValeur}  
        
exp_detail_postule_active:    
    pattern: /Detail-Postule-Active_~{id}
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:DetailPostuleActive}  

exp_list_messages:
    pattern: /exportateur/liste-messages/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:Listemessages}
    
exp_detail_postule_archive:    
    pattern: /Detail-Postule_~{id}/Archive/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:DetailPostuleArchive}  

exp_annuler_postule:        
    pattern: /Supprimer-Postule_~{id}
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:AnnulerPostule}  
        
exp_contrat_encours_detail:        
    pattern: /Contrat-EnCours_~{id}/Detail/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ContratEnCoursDetail}  

exp_contrat_termine_detail:  
    pattern: /Contrat-Terminé_~{id}/Detail/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ContratTermineDetail}  
        
exp_liste_contrats_en_cours:
    pattern: /liste-contrat/encours/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ListeContratEnCours}
    
exp_liste_contrats_termine:
    pattern: /liste-contrat/termine/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ListeContratTermine}

exp_list_notifications:
    pattern: /exportateur/liste-notifications/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:ListeNotifications}
    
ajax_send_msg_exportateur:
    pattern: /message-exportateur-send/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:MessageExportateurSend}    
    
exp_donner_avis_demande_export:  
    pattern: /Exportateur-Demande-Fret_~{id}/Ajout-Avis/
    defaults: {_controller: NzoTunisiefretBundle:Exportateur:DonnerAvisDemandeExport}  
    
#--------------------------- FosUserBundle -----------------------------------
client_registration:
    pattern:  /inscription/client
    defaults: { _controller: NzoUserBundle:RegistrationClient:register }
    
#client_edite_profil:
#    pattern:  /profil/client/edite
#    defaults: { _controller: NzoUserBundle:ProfileClient:edit }    
    
exportateur_registration:
    pattern:  /inscription/exportateur
    defaults: { _controller: NzoUserBundle:RegistrationExportateur:register }

    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profil

   

fos_user_registration_check_email:
    pattern: /check-email
    defaults: { _controller: FOSUserBundle:Registration:checkEmail }
    requirements:
      _method: GET
      
fos_user_registration_confirm:
    pattern: /inscription/confirmer/{token}
    defaults: { _controller: FOSUserBundle:Registration:confirm }
    requirements:
      _method: GET
      
fos_user_registration_confirmed:
    pattern: /inscription/confirmer
    defaults: { _controller: FOSUserBundle:Registration:confirmed }
    requirements:
      _method: GET    
      
# modif bundle to NzoUser      
fos_user_change_password: 
    pattern: /change-password
    defaults: { _controller: NzoUserBundle:ChangePassword:changePassword } 
    requirements:
      _method: GET|POST   
      
      
fos_user_resetting_request:
    pattern: /request
    defaults: { _controller: FOSUserBundle:Resetting:request }
    requirements:
      _method: GET

fos_user_resetting_send_email:
    pattern: /send-email
    defaults: { _controller: FOSUserBundle:Resetting:sendEmail }
    requirements:
      _method: POST

fos_user_resetting_check_email:
    pattern: /check-email
    defaults: { _controller: FOSUserBundle:Resetting:checkEmail }
    requirements:
      _method: GET

fos_user_resetting_reset:
    pattern: /reset/{token}
    defaults: { _controller: FOSUserBundle:Resetting:reset }
    requirements:
      _method: GET|POST

#--------------------------- babababababababaab -----------------------------------
# ADMIN

admin_liste_clients:
    pattern: /admin/liste-clients/
    defaults: { _controller: NzoTunisiefretBundle:Admin:ListeClients }

admin_liste_exportateurs:
    pattern: /admin/liste-exportateurs/
    defaults: { _controller: NzoTunisiefretBundle:Admin:ListeExportateurs }
        