parameters:
#    nzo_tunisiefret.example.class: Nzo\TunisiefretBundle\Example

services:
#    nzo_tunisiefret.example:
#        class: %nzo_tunisiefret.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
